language: node_js
node_js:
  - "4"
before_script:
  - npm install -g gulp
  - npm install
script: gulp package
after_success:
  - if [[ $TRAVIS_BRANCH == 'dev' ]]; then git remote add origin $DEPLOY_REPO; git add .; git commit -m "Build $TRAVIS_BUILD_NUMBER" fi
