language: node_js
node_js:
  - "4"
before_script:
  - npm install -g gulp
script: gulp package
after_success:
  - if [[ $TRAVIS_BRANCH == "dev" ]]; then ./deploy.sh; fi
notifications:
  email: false
