language: node_js
notifications:
  email: false
node_js:
  - '4'
before_install:
  - openssl aes-256-cbc -K $encrypted_d379535e17ca_key -iv $encrypted_d379535e17ca_iv
    -in id_rsa.enc -out id_rsa -d
before_script:
  - npm install -g gulp
  - sleep 10
script: gulp compile
addons:
  ssh_known_hosts: ogdabou.ninja
after_success:
  - if [[ $TRAVIS_BRANCH == "dev" ]]; then chmod 750 deploy.sh; ./deploy.sh; fi
